PRAGMA foreign_keys = ON;

CREATE TABLE users(
  email VARCHAR(40) NOT NULL,
  fullname VARCHAR(40) NOT NULL,
  created DATETIME DEFAULT (DATETIME(CURRENT_TIMESTAMP, 'LOCALTIME')),
  PRIMARY KEY (email)
);

CREATE TABLE admins(
  email VARCHAR(40) NOT NULL,
  FOREIGN KEY (email) REFERENCES users(email) ON DELETE CASCADE
);

CREATE TABLE posts(
  postid INTEGER PRIMARY KEY AUTOINCREMENT,
  type VARCHAR(40) NOT NULL,
  title VARCHAR(64) NOT NULL,
  fullname VARCHAR(40) NOT NULL,
  email VARCHAR(40) NOT NULL,
  text VARCHAR(65536) NOT NULL,
  readCount INTEGER NOT NULL,
  isAnnouncement BOOL NOT NULL,
  created DATETIME DEFAULT (DATETIME(CURRENT_TIMESTAMP, 'LOCALTIME')),
  FOREIGN KEY (email) REFERENCES users(email) ON DELETE CASCADE  -- Added missing comma here
);

CREATE TABLE imgs(
  imgid INTEGER PRIMARY KEY AUTOINCREMENT,
  filename VARCHAR(64) NOT NULL,
  postid INTEGER,
  FOREIGN KEY (postid) REFERENCES posts(postid) ON DELETE CASCADE
);
CREATE TABLE comments(
  commentid INTEGER PRIMARY KEY AUTOINCREMENT,
  email VARCHAR(40) NOT NULL,
  postid INTEGER NOT NULL,
  text VARCHAR(1024) NOT NULL,
  created DATETIME DEFAULT (DATETIME(CURRENT_TIMESTAMP, 'LOCALTIME')),
  isCommentOfComment BOOL NOT NULL,
  parentCommentid INTEGER,
  FOREIGN KEY (email) REFERENCES users(email) ON DELETE CASCADE,
  FOREIGN KEY (postid) REFERENCES posts(postid) ON DELETE CASCADE
);
