-- One-time seed of the /about/members board years 23-24, 24-25 and 25-26,
-- copied from the client's hard-coded src/features/about-page/data/memberPageData.ts.
-- Run once, after the schema. A second run fails on the boardyears primary key
-- and changes nothing.
BEGIN;

INSERT INTO boardyears (startyear, published) VALUES
    (2023, true),
    (2024, true),
    (2025, true);

INSERT INTO boardmembers (startyear, name, major, classyear, roles, islead, tier, position) VALUES
    (2025, 'Jin Wook Shin', 'Computer Engineering', 2027, ARRAY['President Lead'], false, 'president', 0),
    (2025, 'Jisang Um', 'IOE', 2026, ARRAY['Vice President Lead'], false, 'president', 1),
    (2025, 'Jessica Moon', 'Information Analysis', 2027, ARRAY['Event Planning Lead/Finance'], true, 'member', 0),
    (2025, 'Seungmin Shin', 'Statistics', 2025, ARRAY['Event Planning'], false, 'member', 1),
    (2025, 'Joowon Kang', 'Psychology', 2026, ARRAY['Event Planning'], false, 'member', 2),
    (2025, 'Haeun Lee', 'BHS', 2028, ARRAY['Event Planning'], false, 'member', 3),
    (2025, 'Jiwon Byeon', 'International Studies', 2027, ARRAY['Event Planning'], false, 'member', 4),
    (2025, 'Nayeon Bang', 'Biochemistry', 2029, ARRAY['Event Planning'], false, 'member', 5),
    (2025, 'Kaycee Kim', 'Psychology', 2029, ARRAY['Event Planning'], false, 'member', 6),
    (2025, 'Hyunjun Seo', 'Chemistry', 2027, ARRAY['Event Planning'], false, 'member', 7),
    (2025, 'Miran Kim', 'Movement Science', 2029, ARRAY['Event Planning'], false, 'member', 8),
    (2025, 'Junhee Han', 'Mechanical Engineering / Chemical Engineering', 2028, ARRAY['Finance'], false, 'member', 9),
    (2025, 'Junho Lee', 'Education', 2028, ARRAY['Outreach Lead'], true, 'member', 10),
    (2025, 'Rachel Lee', 'Data Science', 2028, ARRAY['Outreach/Website'], false, 'member', 11),
    (2025, 'Jiwoo Kim', 'Chemical Engineering', 2026, ARRAY['Outreach'], false, 'member', 12),
    (2025, 'Sejong Kim', 'Data Science', 2029, ARRAY['Outreach'], false, 'member', 13),
    (2025, 'Yunseong Na', 'Computer Science', 2026, ARRAY['Web Development Lead'], true, 'member', 14),
    (2025, 'Hannah Lee', 'Data Science', 2027, ARRAY['Web Development'], false, 'member', 15),
    (2025, 'Doohee Nam', 'Computer Science, Statistics', 2028, ARRAY['Web Development'], false, 'member', 16),
    (2025, 'Jaeyi Kang', 'Computer Engineering', 2028, ARRAY['Web Development/Outreach'], false, 'member', 17),
    (2025, 'Soobin Ihm', 'Chemistry', 2028, ARRAY['Web Development'], false, 'member', 18),
    (2025, 'Hyo Won Ko', 'Statistics', 2026, ARRAY['Social Media/Marketing Lead'], true, 'member', 19),
    (2025, 'Hyeri Lee', 'Electrical Engineering', 2026, ARRAY['Social Media/Marketing'], false, 'member', 20),
    (2025, 'Younghyun Choi', 'Psychology', 2026, ARRAY['Social Media/Marketing'], false, 'member', 21),
    (2025, 'Sarah Kim', 'Neuroscience', 2026, ARRAY['Social Media/Marketing'], false, 'member', 22),
    (2025, 'Emma Choi', 'Economics', 2029, ARRAY['Social Media/Marketing'], false, 'member', 23),
    (2025, 'Eva Choi', 'Biology', 2029, ARRAY['Social Media/Marketing'], false, 'member', 24),
    (2025, 'Sangyong Park', 'Electrical Engineering', 2027, ARRAY['Social Media/Marketing'], false, 'member', 25),
    (2025, 'Dayoung Kang', 'Neuroscience', 2027, ARRAY['Social Media/Marketing'], false, 'member', 26),
    (2025, 'Soomin Kang', 'Pharmaceutical Science', 2028, ARRAY['Design Lead'], true, 'member', 27),
    (2025, 'Kelly Koo', 'BHS & Art and Design', 2027, ARRAY['Design'], false, 'member', 28),
    (2025, 'Jimin Oh', 'Fine Arts', 2028, ARRAY['Design'], false, 'member', 29),
    (2025, 'Esther Kim', 'Art & Design', 2029, ARRAY['Design'], false, 'member', 30),
    (2024, 'Jaemin Jeon', 'Computer Science', 2025, ARRAY['President'], false, 'president', 0),
    (2024, 'Jin Wook Shin', 'Computer Engineering', 2026, ARRAY['Vice President - OP'], false, 'president', 1),
    (2024, 'Seoyeon Han', 'Computer Science', 2025, ARRAY['Vice President - PR'], false, 'president', 2),
    (2024, 'Jihyun Park', 'Economics', 2025, ARRAY['Finance'], false, 'member', 0),
    (2024, 'Jisang Um', 'IOE', 2026, ARRAY['Operational Support'], false, 'member', 1),
    (2024, 'Yoon Sung Ji', 'Computer Science', 2025, ARRAY['Event Planning'], false, 'member', 2),
    (2024, 'Yoonseo Shin', 'Computer Science', 2026, ARRAY['Web Development', 'Event Planning'], false, 'member', 3),
    (2024, 'Sophia Chang', 'Robotics', 2027, ARRAY['Event Planning'], false, 'member', 4),
    (2024, 'Jessica Moon', 'Undecided', 2027, ARRAY['Event Planning'], false, 'member', 5),
    (2024, 'Haeun Lee', 'BHS', 2028, ARRAY['Event Planning'], false, 'member', 6),
    (2024, 'Junhee Han', 'Undecided', 2028, ARRAY['Event Planning'], false, 'member', 7),
    (2024, 'Dongsub Kim', 'Computer Science', 2023, ARRAY['Web Development Lead'], true, 'member', 8),
    (2024, 'Jioh In', 'Computer Science', 2028, ARRAY['Web Development'], false, 'member', 9),
    (2024, 'Hannah Lee', 'Data Science', 2027, ARRAY['Web Development'], false, 'member', 10),
    (2024, 'Yunseong Na', 'Computer Science', 2026, ARRAY['Web Development'], false, 'member', 11),
    (2024, 'Seungmin Shin', 'Statistics', 2025, ARRAY['Outreach Lead'], true, 'member', 12),
    (2024, 'Wookwan Kwon', 'Computer Science', 2024, ARRAY['Outreach'], false, 'member', 13),
    (2024, 'Junho Lee', 'Education', 2028, ARRAY['Outreach'], false, 'member', 14),
    (2024, 'Dongeun Kim', 'Data Science', 2028, ARRAY['Web Development', 'Outreach'], false, 'member', 15),
    (2024, 'Rachel Lee', 'BME', 2028, ARRAY['Outreach'], false, 'member', 16),
    (2024, 'Minjun Hur', 'BME', 2026, ARRAY['Outreach'], false, 'member', 17),
    (2024, 'Jungin Hwang', 'Computer Science', 2026, ARRAY['Design Lead / Web UI Design'], true, 'member', 18),
    (2024, 'Kelly Koo', 'BHS & Art and Design', 2027, ARRAY['Design'], false, 'member', 19),
    (2024, 'Soomin Kang', 'Undeclared', 2028, ARRAY['Design'], false, 'member', 20),
    (2024, 'Lauren Kim', 'Computer Science', 2026, ARRAY['Web Development', 'Design'], false, 'member', 21),
    (2024, 'Hyeri Lee', 'Electrical Engineering', 2026, ARRAY['Social Media/Marketing'], false, 'member', 22),
    (2024, 'Chaeyoung Kim', 'Biomedical Engineering', 2026, ARRAY['Social Media/Marketing'], false, 'member', 23),
    (2024, 'Hyowon Ko', 'Statistics', 2027, ARRAY['Social Media/Marketing'], false, 'member', 24),
    (2024, 'Cloe Jung', 'Psychology', 2026, ARRAY['Social Media/Marketing'], false, 'member', 25),
    (2024, 'Younghyun Choi', 'Psychology', 2026, ARRAY['Social Media/Marketing'], false, 'member', 26),
    (2024, 'Joowon Kang', 'Psychology', 2026, ARRAY['Social Media/Marketing'], false, 'member', 27),
    (2024, 'Sarah Kim', 'Neuroscience', 2027, ARRAY['Social Media/Marketing'], false, 'member', 28),
    (2023, 'Wookwan Kwon', 'Computer Science', 2024, ARRAY['President'], false, 'president', 0),
    (2023, 'Yuri Hong', 'Electrical Engineering', 2026, ARRAY['Vice President - OP'], false, 'president', 1),
    (2023, 'Siwon Lee', 'Communication & Media', 2024, ARRAY['Vice President - PR'], false, 'president', 2),
    (2023, 'Jihyun Park', 'Economics', 2025, ARRAY['Finance'], false, 'member', 0),
    (2023, 'Kyungmin Inn', 'Computer Engineering', 2027, ARRAY['Operational Support'], false, 'member', 1),
    (2023, 'Yoon Sung Ji', 'Computer Science', 2025, ARRAY['Event Planning'], false, 'member', 2),
    (2023, 'Jinwook Shin', 'Computer Engineering', 2026, ARRAY['Event Planning'], false, 'member', 3),
    (2023, 'Jaemin Jeon', 'Computer Science', 2025, ARRAY['Event Planning'], false, 'member', 4),
    (2023, 'Jisang Um', 'IOE', 2026, ARRAY['Operational Support'], false, 'member', 5),
    (2023, 'Dongsub Kim', 'Computer Science', 2023, ARRAY['Web Development Lead'], true, 'member', 6),
    (2023, 'Jioh In', 'Computer Science', 2028, ARRAY['Web Development'], false, 'member', 7),
    (2023, 'Chaeyoon Park', 'STAMPS', 2025, ARRAY['Design Lead'], true, 'member', 8),
    (2023, 'Kelly Koo', 'BHS', 2027, ARRAY['Design'], false, 'member', 9),
    (2023, 'Jade Byeon', 'STAMPS & Statistics', 2026, ARRAY['Design'], false, 'member', 10),
    (2023, 'Jungin Hwang', 'Computer Science', 2026, ARRAY['Design'], false, 'member', 11),
    (2023, 'Hyeri Lee', 'Electrical Engineering', 2026, ARRAY['Social Media/Marketing'], false, 'member', 12),
    (2023, 'Chaeyoung Kim', 'Biomedical Engineering', 2026, ARRAY['Social Media/Marketing'], false, 'member', 13),
    (2023, 'Hyowon Ko', 'Statistics', 2027, ARRAY['Social Media/Marketing'], false, 'member', 14),
    (2023, 'Stella Han', 'Computer Science', 2025, ARRAY['Social Media/Marketing'], false, 'member', 15),
    (2023, 'Yoonjoo Lee', 'Art History & Philosophy', 2025, ARRAY['Outreach Lead'], true, 'member', 16),
    (2023, 'Huymin Lee', 'Data Science & Statistics', 2024, ARRAY['Outreach'], false, 'member', 17),
    (2023, 'Jooyoung Chung', 'Political Science & Pre-Med', 2024, ARRAY['Outreach'], false, 'member', 18),
    (2023, 'Seungmin Shin', 'Statistics', 2025, ARRAY['Outreach'], false, 'member', 19),
    (2023, 'Sophia Jang', 'Robotics', 2027, ARRAY['Outreach'], false, 'member', 20);

COMMIT;
