-- Supabase/Postgres schema for the KISA Flask API.
-- Run in a scratch Supabase project first. Table and column names are lowercase
-- because the current Flask SQL does not quote identifiers.

CREATE TABLE IF NOT EXISTS users (
    email varchar(255) PRIMARY KEY,
    fullname varchar(255) NOT NULL,
    bornyear integer NOT NULL,
    bornmonth integer NOT NULL CHECK (bornmonth BETWEEN 1 AND 12),
    borndate integer NOT NULL CHECK (borndate BETWEEN 1 AND 31),
    major varchar(255) NOT NULL,
    gradyear integer NOT NULL,
    linkedin text,
    created timestamp NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS admins (
    email varchar(255) PRIMARY KEY REFERENCES users(email) ON DELETE CASCADE,
    created timestamp NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS posts (
    postid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    type varchar(64) NOT NULL,
    email varchar(255) REFERENCES users(email) ON DELETE SET NULL,
    title varchar(255) NOT NULL,
    text text NOT NULL,
    isannouncement boolean NOT NULL DEFAULT false,
    fullname varchar(255) NOT NULL,
    readcount integer NOT NULL DEFAULT 0 CHECK (readcount >= 0),
    anonymous boolean NOT NULL DEFAULT false,
    created timestamp NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS comments (
    commentid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(255) NOT NULL REFERENCES users(email) ON DELETE CASCADE,
    postid integer NOT NULL REFERENCES posts(postid) ON DELETE CASCADE,
    text text NOT NULL,
    iscommentofcomment boolean NOT NULL DEFAULT false,
    parentcommentid integer REFERENCES comments(commentid) ON DELETE CASCADE,
    anonymous boolean NOT NULL DEFAULT false,
    secret boolean NOT NULL DEFAULT false,
    created timestamp NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS postlikes (
    email varchar(255) NOT NULL REFERENCES users(email) ON DELETE CASCADE,
    postid integer NOT NULL REFERENCES posts(postid) ON DELETE CASCADE,
    created timestamp NOT NULL DEFAULT now(),
    PRIMARY KEY (email, postid)
);

CREATE TABLE IF NOT EXISTS commentlikes (
    email varchar(255) NOT NULL REFERENCES users(email) ON DELETE CASCADE,
    commentid integer NOT NULL REFERENCES comments(commentid) ON DELETE CASCADE,
    created timestamp NOT NULL DEFAULT now(),
    PRIMARY KEY (email, commentid)
);

CREATE TABLE IF NOT EXISTS pocha (
    pochaid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    startdate timestamp NOT NULL,
    enddate timestamp NOT NULL,
    title varchar(32) NOT NULL,
    description varchar(1024) NOT NULL,
    CHECK (startdate < enddate)
);

CREATE TABLE IF NOT EXISTS menu (
    menuid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    namekor varchar(32) NOT NULL,
    nameeng varchar(32) NOT NULL,
    category varchar(32) NOT NULL,
    price double precision NOT NULL CHECK (price >= 0),
    stock integer NOT NULL CHECK (stock >= 0),
    isimmediateprep boolean NOT NULL,
    parentpochaid integer NOT NULL REFERENCES pocha(pochaid) ON DELETE CASCADE,
    agecheckrequired boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS "order" (
    orderid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email varchar(255) REFERENCES users(email) ON DELETE SET NULL,
    parentpochaid integer NOT NULL REFERENCES pocha(pochaid) ON DELETE CASCADE,
    ispaid boolean NOT NULL DEFAULT false
);

CREATE TABLE IF NOT EXISTS orderitem (
    orderitemid integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status varchar(16) NOT NULL CHECK (status IN ('pending', 'preparing', 'ready', 'closed')),
    quantity integer NOT NULL CHECK (quantity > 0),
    parentorderid integer NOT NULL REFERENCES "order"(orderid) ON DELETE CASCADE,
    menuid integer NOT NULL REFERENCES menu(menuid) ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS notificationarns (
    email varchar(255) PRIMARY KEY REFERENCES users(email) ON DELETE CASCADE,
    endpointarn text NOT NULL,
    created timestamp NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_posts_type_announcement_postid
    ON posts(type, isannouncement, postid DESC);
CREATE INDEX IF NOT EXISTS idx_posts_email_anonymous
    ON posts(email, anonymous);
CREATE INDEX IF NOT EXISTS idx_comments_post_parent
    ON comments(postid, iscommentofcomment, parentcommentid);
CREATE INDEX IF NOT EXISTS idx_comments_email_anonymous
    ON comments(email, anonymous);
CREATE INDEX IF NOT EXISTS idx_menu_parentpochaid
    ON menu(parentpochaid);
CREATE INDEX IF NOT EXISTS idx_order_email_pocha_paid
    ON "order"(email, parentpochaid, ispaid);
CREATE INDEX IF NOT EXISTS idx_orderitem_parent_status
    ON orderitem(parentorderid, status);
